block-beta
    columns 5
    A1 space space space B1
    space space space space space
    A2 space space space B2
    space space space space space
    A3 space E space B3

    A1 --> A2
    A2 --> A3

    B1 --> B2
    B2 --> B3

    A3 --> E
    B3 --> E