block-beta
    block
        columns 1
        a["Client"] b["Client stub"] c["RPC runtime"]
    end
    block
        columns 1
        a1["Client"] b2["Client stub"] c1["RPC runtime"]
    end
    c --> c1
