@startuml
title client streaming RPC

participant "gRPC Client" as Client
participant "gRPC Server" as Server

Client -> Server: requestObserver.onNext("one")
activate Server

Client -> Server: requestObserver.onNext("two")
Client -> Server: requestObserver.onNext("three")
Client -> Server: requestObserver.onComplete()

Server -> Client: response.onNext(EchoResponse)
Server -> Client: response.onCompleted()
deactivate Server

@enduml
