@startuml
title Server Streaming RPC

participant "gRPC Client" as Client
participant "gRPC Server" as Server

Client -> Server: serverStreamingEcho(EchoRequest)
activate Server

loop for each response
  Server -> Client: onNext(EchoResponse)
end

Server -> Client: onCompleted()
deactivate Server

@enduml
