@startuml
title server streaming RPC

participant "gRPC Client" as Client
participant "gRPC Server" as Server

Client -> Server: serverStreamingEcho(EchoRequest)

activate Server
Server -> Client: onNext(EchoResponse)
Server -> Client: onNext(EchoResponse)
Server -> Client: onNext(EchoResponse)
Server -> Client: onCompleted()
deactivate Server

@enduml
