@startuml
title Unary gRPC

participant "gRPC Client" as Client
participant "gRPC Server" as Server

Client -> Server: unaryEcho(EchoRequest)

activate Server
Server -> Client: onNext(EchoResponse)
Server -> Client: onCompleted()
deactivate Server

@enduml
