@startuml
!theme mono
scale 1.1
hide footbox
title gRPC server-side streaming
skinparam TitleFontStyle plain
skinparam TitleFontSize 14
skinparam sequenceMessageAlign center

participant client
participant server

client ->>(5) server: serverStreamingEcho(request)

alt success
    server ->>(5) client: onNext(response)
    server ->>(5) client: onNext(response)
    server ->>(5) client: onNext(response)
    server ->>(5) client: onCompleted()
else failure
    server ->>(5) client: onError(error)
end
@enduml
