@startuml
!theme plain
scale 1.0
title gRPC life cycle
skinparam TitleFontStyle plain
skinparam TitleFontSize 14
skinparam defaultTextAlignment center
skinparam linetype ortho

card "client" as C0
card "channel" as C1
card "client stub" as C2
card "gRPC runtime" as C3
card "transport" as C4

card "server" as S0
card "service" as S1
card "service stub" as S2
card "gRPC runtime" as S3
card "transport" as S4

card "ProtoBuf" as P
card "HTTP/2" as H

C0 -d- C1
C1 -d- C2
C2 -d- C3
C3 -d- C4
C3 -[hidden]d- C4
C3 -[hidden]d- C4
C3 -[hidden]d- C4

S0 -d- S1
S1 -d- S2
S2 -d- S3
S3 -d- S4
S3 -[hidden]d- S4
S3 -[hidden]d- S4
S3 -[hidden]d- S4

C2 -[dotted]r- P
P -[dotted]r- S2

C4 -r- H
H -r- S4

@enduml
