@startuml
!theme plain
scale 1.0
skinparam defaultTextAlignment center
skinparam linetype ortho

rectangle "Client" as C0
rectangle "Channel" as C1
rectangle "Client stub" as C2
rectangle "gRPC runtime" as C3
rectangle "Transport" as C4

rectangle "Server" as S0
rectangle "Service" as S1
rectangle "Service stub" as S2
rectangle "gRPC runtime" as S3
rectangle "Transport" as S4

rectangle "ProtoBuf" as P
rectangle "HTTP/2" as H

C0 -d- C1
C1 -d- C2
C2 -d- C3
C3 -d- C4
C3 -[hidden]d- C4
C3 -[hidden]d- C4
C3 -[hidden]d- C4

S0 -d- S1
S1 -d- S2
S2 -d- S3
S3 -d- S4
S3 -[hidden]d- S4
S3 -[hidden]d- S4
S3 -[hidden]d- S4

C2 -[dotted]r- P
P -[dotted]r- S2

C4 -r- H
H -r- S4

@enduml
