@startuml
!theme plain
'!pragma layout smetana
scale 1.1
skinparam defaultTextAlignment center
skinparam linetype ortho

rectangle "Client" as C0
rectangle "Channel" as C1
rectangle "Client stub" as C2
rectangle "gRPC runtime" as C3
rectangle "Transport" as C4

rectangle "Server" as S0
rectangle "Service" as S1
rectangle "Service stub" as S2
rectangle "gRPC runtime" as S3
rectangle "Transport" as S4

rectangle "ProtoBuf" as P
rectangle "HTTP/2" as H

C0 -down- C1
C1 -down- C2
C2 -down- C3
C3 -down- C4

S0 -down- S1
S1 -down- S2
S2 -down- S3
S3 -down- S4

C2 -[dotted]right- P
P -[dotted]right- S2

C4 --right-- H
H --right-- S4

@enduml
