@startuml
'!pragma teoz true
!theme mono
scale 1.1
'title Remote Procedure Calls (RPC)
hide footbox
'skinparam monochrome true
skinparam TitleFontStyle plain
'skinparam defaultFontName Source Sans Pro
'skinparam titleFontSize 15
skinparam sequenceMessageAlign center

participant "client" as Client
participant "server" as Server

activate Client
note left of Client: invoke procedure
Client ->> Server : procedure call
deactivate Client
activate Server

note right of Server: receive parameters
note right of Server: execute procedure
note right of Server: send result

Server ->> Client : result from procedure execution
deactivate Server
activate Client

||40||
'client -[#white]->]

@enduml
