@startuml

skinparam linetype ortho

rectangle "client" as C1
rectangle "client stub" as C2
rectangle "gRPC runtime" as C3

rectangle "server" as S1
rectangle "service stub" as S2
rectangle "gRPC runtime" as S3

file ".proto" as P
card "HTTP/2" as H

C1 -down- C2
C2 -down- C3

S1 -down- S2
S2 -down- S3

C2 --[dotted]right-- P
P --[dotted]right-- S2

C3 -right- H
H -right- S3

@enduml
