@startuml

skinparam linetype ortho

'skinparam monochrome true
'skinparam defaultFontName Source Sans Pro
'skinparam titleFontSize 15
'skinparam sequenceMessageAlign left
'skinparam participantBackgroundColor #white
'skinparam noteBackgroundColor #white
'skinparam sequenceGroupBackgroundColor #white

rectangle "Client" as C1
rectangle "Client stub" as C2
rectangle "gRPC runtime" as C3

rectangle "Server" as S1
rectangle "Service stub" as S2
rectangle "gRPC runtime" as S3

file ".proto" as P
card "HTTP/2" as H

C1 -down- C2
C2 -down- C3

S1 -down- S2
S2 -down- S3

C2 --[dotted]right-- P
P --[dotted]right-- S2

C3 -right- H
H -right- S3

@enduml
